name: Snapshot

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run fetch
      - run: |
          DATE=$(date +"%d/%m/%y")
          DIFF_LINES=$(git diff | wc -l)
          if [ $DIFF_LINES -gt 0  ]
          then
            git config --global user.email "bot@magmatic.xyz"
            git config --global user.name "Magmatic Bot"
            git add .
            git commit -m "Snapshot lists: $DATE"
            git push
          fi
          git tag "$DATE"
          git push origin "$DATE"
